"use client";
import { ChangeEvent, useEffect, useRef, useState } from "react";
const W=1206,H=2622; type Layer="island"|"dock"|"icons"|"widgets";
const choices:Record<Layer,{name:string;color:string}[]>={island:[{name:"Nenhum",color:"transparent"},{name:"Glass",color:"rgba(255,255,255,.28)"},{name:"Midnight",color:"rgba(5,8,18,.82)"},{name:"Aurora",color:"rgba(123,92,255,.52)"}],dock:[{name:"Nenhum",color:"transparent"},{name:"Frost",color:"rgba(255,255,255,.24)"},{name:"Smoke",color:"rgba(15,20,32,.48)"},{name:"Violet",color:"rgba(122,92,255,.36)"}],icons:[{name:"Nenhum",color:"transparent"},{name:"Outline",color:"rgba(255,255,255,.4)"},{name:"Dark",color:"rgba(7,10,18,.48)"},{name:"Lilac",color:"rgba(159,125,255,.38)"}],widgets:[{name:"Nenhum",color:"transparent"},{name:"Glass",color:"rgba(255,255,255,.22)"},{name:"Ink",color:"rgba(9,13,24,.55)"},{name:"Gradient",color:"rgba(103,70,255,.42)"}]};
export default function Home(){
 const canvasRef=useRef<HTMLCanvasElement>(null),fileRef=useRef<HTMLInputElement>(null);const[image,setImage]=useState<HTMLImageElement|null>(null),[stage,setStage]=useState<"landing"|"editor">("landing"),[active,setActive]=useState<Layer>("island"),[selected,setSelected]=useState<Record<Layer,number>>({island:1,dock:1,icons:0,widgets:0});
 useEffect(()=>{const c=canvasRef.current;if(!c||!image)return;const ctx=c.getContext("2d");if(!ctx)return;const scale=Math.max(W/image.width,H/image.height),dw=image.width*scale,dh=image.height*scale;ctx.clearRect(0,0,W,H);ctx.drawImage(image,(W-dw)/2,(H-dh)/2,dw,dh);drawFrames(ctx,selected)},[image,selected,stage]);
 function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{setImage(img);setStage("editor");URL.revokeObjectURL(url)};img.src=url}
 function download(){const canvas=canvasRef.current;if(!canvas)return;canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="framewallmaker-iphone-17-pro.png";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)},"image/png",1)}
 if(stage==="landing")return <main className="landingPage"><nav><a className="brand" href="#">framewall<span>maker</span></a><div className="navMeta"><b>iPhone 17 Pro</b><span>1206 × 2622 px</span></div></nav><section className="hero landingHero"><div className="copy"><span className="eyebrow">WALLPAPER STUDIO</span><h1>Seu wallpaper.<br/><em>Perfeitamente enquadrado.</em></h1><p>Envie uma imagem para abrir o estúdio. Na próxima tela você poderá visualizar e aplicar todos os frames.</p><button className="primary" onClick={()=>fileRef.current?.click()}>Escolher imagem <span>↗</span></button><input ref={fileRef} hidden type="file" accept="image/*" onChange={upload}/><small>JPG, PNG, WEBP ou HEIC · Processamento no seu aparelho</small></div><div className="landingVisual"><div className="miniPhone"><div className="miniIsland"/><div className="miniGlow"/><div className="miniDock"/></div><span>PRONTO PARA O IPHONE 17 PRO</span></div></section><footer><b>Feito para iPhone 17 Pro</b><span>Sua imagem não é enviada para nenhum servidor.</span></footer></main>;
 return <main className="editorPage"><nav><button className="backTop" onClick={()=>setStage("landing")}>← Voltar</button><a className="brand" href="#">framewall<span>maker</span></a><button className="finishTop" onClick={download}>Concluir e baixar ↓</button></nav><section className="workspace"><button className="side left" aria-label="Voltar" onClick={()=>setStage("landing")}>←<small>Voltar</small></button><div className="expandedPhone"><canvas ref={canvasRef} width={W} height={H}/><div className="phoneLabel"><i/> EDIÇÃO EM TEMPO REAL</div></div><button className="side right" aria-label="Concluir e baixar" onClick={download}>↓<small>Concluir</small></button></section><section className="studio editorStudio"><div className="tabs">{(["island","dock","icons","widgets"] as Layer[]).map(x=><button key={x} className={active===x?"active":""} onClick={()=>setActive(x)}>{x==="island"?"Notch":x==="dock"?"Dock":x==="icons"?"Ícones":"Widgets"}</button>)}</div><div className="styles">{choices[active].map((x,i)=><button key={x.name} className={selected[active]===i?"chosen":""} onClick={()=>setSelected(s=>({...s,[active]:i}))}><span style={{background:x.color}}/><b>{x.name}</b>{selected[active]===i&&<i>✓</i>}</button>)}</div><button className="download" onClick={download}>Concluir e baixar wallpaper<span>↓</span></button></section></main>
}
function rr(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawFrames(ctx:CanvasRenderingContext2D,s:Record<Layer,number>){const island=choices.island[s.island].color;if(island!=="transparent"){ctx.fillStyle=island;ctx.shadowColor="rgba(0,0,0,.25)";ctx.shadowBlur=25;rr(ctx,402,48,402,112,58);ctx.shadowBlur=0}const dock=choices.dock[s.dock].color;if(dock!=="transparent"){ctx.fillStyle=dock;ctx.strokeStyle="rgba(255,255,255,.28)";ctx.lineWidth=3;rr(ctx,54,2268,1098,270,86);ctx.stroke()}const icon=choices.icons[s.icons].color;if(icon!=="transparent"){ctx.fillStyle=icon;ctx.strokeStyle="rgba(255,255,255,.28)";ctx.lineWidth=3;for(const x of [72,348,624,900])for(const y of [342,630,918,1206,1494,1782]){rr(ctx,x,y,234,234,56);ctx.stroke()}}const widget=choices.widgets[s.widgets].color;if(widget!=="transparent"){ctx.fillStyle=widget;ctx.strokeStyle="rgba(255,255,255,.3)";ctx.lineWidth=3;rr(ctx,66,330,501,501,72);ctx.stroke();rr(ctx,66,876,1074,501,72);ctx.stroke();rr(ctx,66,1422,1074,1062,72);ctx.stroke()}}
